home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    #post list
    url(r'^$',views.index_view,name='index'),
    #register
    url(r'^register/$',views.RegistrationFormView.as_view(),name='register'),
    #login
    url(r'^login/$',views.login_form_view,name='login'),
    #logout
    url(r'^logout/$',views.logout_view,name='logout'),
    # faq
    url(r'^faq/$',views.faq_view,name='faq'),
    #profile
    url(r'^user/(?P<user_id>[0-9]+)/profile/$',views.profile_view,name='profile'),
    #profile update
    url(r'^user/(?P<pk>[0-9]+)/profile/update/$',views.UpdateProfile.as_view(),name='profile_update'),
    #single post details
    url(r'^(?P<post_id>[0-9]+)/$',views.single_post,name='single_post'),
    #add new post
    url(r'^post/newpost/$',views.AddPost.as_view(),name='new_post'),
    #update post
    url(r'^post/update/(?P<pk>[0-9]+)/$',views.UpdatePost.as_view(),name='update_post'),
    #delete post
    url(r'^post/delete/(?P<pk>[0-9]+)/$',views.DeletePost.as_view(),name='delete_post'),
    #post comment
    url(r'^post/comment/(?P<post_id>[0-9]+)/$',views.post_comment,name='post_comment'),
    #commnet_delete
    url(r'^post/(?P<post_id>[0-9]+)/comment/(?P<cmnt_id>[0-9]+)/delete/$',views.comment_delete,name='comment_delete'),
    #comment_update
    url(r'^post/comment/(?P<cmnt_id>[0-9]+)/update/$',views.comment_update,name='comment_update'),
    #comment up/down vote
    url(r'^post/(?P<post_id>[0-9]+)/comment/(?P<cmnt_id>[0-9]+)/vote/(?P<vote_type>[0-1])$',views.comment_vote_handler,name='comment_vote'),
    #post follow
    url(r'^post/follow/(?P<post_id>[0-9]+)/$',views.post_follow,name='post_follow'),
    #post up down vote
    url(r'^post/(?P<post_id>[0-9]+)/vote/(?P<vote_type>[0-1])$',views.post_vote_handler,name='post_vote'),
]

sustforum/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from channels import Group
from .settings import MSG_TYPE_MESSAGE
from django.http import JsonResponse

class Post(models.Model):
    title = models.TextField(max_length=1000)
    post = models.TextField(max_length=5000)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField()

    def get_absolute_url(self):
        return reverse('home:single_post',kwargs={'post_id':self.pk})

    def __str__(self):
        return str(self.pk)+" "+str(self.title) + " - "+ str(self.author)


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    author_id = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField()
    vote = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('home:single_post',kwargs={'post_id':self.post.pk})

    def get_last_id(self):
        response = {
            'id':self.id,
            'propic':UserInfo.objects.get(user=self.author_id).propic.url
        }
        return JsonResponse(response)

    def __str__(self):
        return str(self.pk)+" "+self.comment

class Reply(models.Model):
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE)
    reply = models.TextField(max_length=1000)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField()
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.reply+" "+self.user.username

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return  self.name

class PostTag(models.Model):
    post_id = models.IntegerField()
    tag_id = models.IntegerField()

class PostVote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post_id = models.IntegerField()
    vote_type = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)+" "+str(self.post_id)+" "+str(self.vote_type)

    def get_absolute_url(self):
        return reverse('home:single_post',kwargs={'post_id':self.post_id})

class PostFollowed(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post_id = models.IntegerField()

    def __str__(self):
        return str(self.user)+" "+str(self.post_id)

    def get_absolute_url(self):
        return reverse('home:single_post',kwargs={'post_id':self.post_id})

class CommentVote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post_id = models.IntegerField()
    cmnt_id = models.IntegerField()
    vote_type = models.IntegerField(default=0)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)+" "+str(self.cmnt_id)+" "+str(self.vote_type)

    def get_absolute_url(self):
        return reverse('home:single_post',kwargs={'post_id':self.post_id})


class Room(models.Model):
    """
    A room for people to chat in.
    """
    title = models.CharField(max_length=255)
    staff_only = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def websocket_group(self):
        """
        Returns the Channels Group that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return Group("room-%s" % self.id)

    def send_message(self, message, user, msg_type=MSG_TYPE_MESSAGE):
        """
        Called to send a message to the room on behalf of a user.
        """
        final_msg = {'room': str(self.id), 'message': message, 'username': user.username, 'msg_type': msg_type}

        # Send out the message to everyone in the room
        self.websocket_group.send(
            {"text": json.dumps(final_msg)}
        )

class UserInfo(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    firstname = models.CharField(max_length=255,default="not set")
    lastname = models.CharField(max_length=255,default="not set")
    propic = models.FileField(default='default.png',blank=True)
    profession = models.CharField(max_length=255,blank=True)
    color = models.CharField(max_length=255,default="#46b8da")

    def __str__(self):
        return "info : "+self.firstname

    def get_absolute_url(self):
        return reverse('home:profile',kwargs={'user_id':self.user.pk})

class Faq(models.Model):
    question = models.CharField(max_length=1000)
    answer = models.TextField()

    def __str__(self):
        return self.question

home/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForms(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class CommentForm(forms.Form):
    comment = forms.CharField()

class UserInfoForm(forms.Form):
    propic = forms.FileField()
    firstname = forms.CharField()
    lastname = forms.CharField()
    profession = forms.CharField()
    color = forms.CharField()

home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import UserForms,LoginForm,CommentForm,UserInfoForm
from .models import Post,Comment,Reply,PostTag,Tag,PostVote,PostFollowed,CommentVote,Room,UserInfo,User,Faq
from datetime import datetime
from django.core.urlresolvers import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from operator import itemgetter
import random


ara = ["#f9ecf9","#e6ffff","#f2ffcc","#e6f9ff","#e6ecff","#fff0b3","#f9e6ff"]

# login and logout and register

class RegistrationFormView(View):
    form_class = UserForms
    template_name = 'home/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()


            #returns user objects if credentials is correct
            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    userinfo = UserInfo()
                    userinfo.user = user
                    userinfo.save()
                    login(request,user)
                    return redirect('home:index')

        return render(request,self.template_name,{'form':form})


def login_form_view(request):
    form = LoginForm(request.POST or None)
    template_name = 'home/login_form.html'

    if form.is_valid():

        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        # returns user objects if credentials is correct
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('home:index')

    return render(request, template_name, {'form': form})

def logout_view(request):
    if request.user.is_authenticated():
        logout(request)
        return redirect('home:index')
    raise Http404("user not loged in")

def index_view(request):
    template_name = 'home/index.html'
    all_post=[]
    all_posts = Post.objects.all().order_by('-id')
    for post in all_posts:
        temp=dict()
        temp['post']=post
        temp['color']=ara[random.randint(0, 6)]
        try:
            temp['uinfo']=UserInfo.objects.filter(user=post.author)[0]
            print temp['uinfo']
        except:
            pass
        all_post.append(temp)

    rooms = Room.objects.order_by("title")
    recent = Post.objects.all().order_by('-id')[:5]
    followed = []
    if request.user.is_authenticated():
        temp = PostFollowed.objects.filter(user=request.user).order_by('-id')[:5]
        for t in temp:
            followed.append(Post.objects.filter(pk=t.post_id)[0])

    query = request.GET.get("q")
    if query:
        all_post=[]
        all_posts =all_posts.filter(
            Q(title__icontains=query) |
            Q(post__icontains=query) |
            Q(author__username__icontains=query)
        ).distinct()

        for post in all_posts:
            temp = dict()
            temp['post'] = post
            temp['color'] = ara[random.randint(0, 6)]
            try:
                temp['uinfo'] = UserInfo.objects.get(user=post.author)
                print temp['uinfo']
            except:
                pass
            all_post.append(temp)

    paginator = Paginator(all_post, 10)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        paginated_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        paginated_posts = paginator.page(paginator.num_pages)

    context = {
        'all_post': paginated_posts,
        'recent': recent,
        'followed': followed,
        'room':rooms[0],
        'username':request.user.username
    }

    return render(request, template_name, context)

def single_post(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    edit = post.author==request.user
    delete = request.user.is_superuser
    recent = Post.objects.all().order_by('-id')[:5]
    comments = Comment.objects.filter(post=post)
    rooms = Room.objects.order_by("title")
    all_comments=[]
    for com in comments:
        wrap = dict()
        cuv = CommentVote.objects.filter(cmnt_id=com.pk, vote_type=1).count()
        cdv = CommentVote.objects.filter(cmnt_id=com.pk, vote_type=-1).count()
        com.vote = cuv - cdv

        wrap["comment"] = com
        try:
            wrap["propic"] = UserInfo.objects.get(user=com.author_id).propic.url
        except:
            pass
        all_comments.append(wrap)

    follow = "unfollow"
    followed = []
    if request.user.is_authenticated():
        temp = PostFollowed.objects.filter(user=request.user).order_by('-id')[:5]
        for t in temp:
            followed.append(Post.objects.filter(pk=t.post_id)[0])
        f = PostFollowed.objects.filter(user=request.user,post_id=post_id).count()
        if f==0:
            follow = "follow"
    uv = PostVote.objects.filter(post_id=post_id,vote_type=1).count()
    dv = PostVote.objects.filter(post_id=post_id,vote_type=-1).count()
    vote = uv-dv
    temmp=0
    context = {
        'post': post,
        'edit':edit,
        'delete':delete,
        'vote':vote,
        'comments':all_comments,
        'follow':follow,
        'recent':recent,
        'followed':followed,
        'room':rooms[0],
        'username': request.user.username
    }
    return render(request, 'home/single_post.html', context)

@method_decorator(login_required, name='dispatch')
class AddPost(CreateView):
    model = Post
    fields = ['title','post']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.date = datetime.now()
        obj.save()
        return redirect(obj.get_absolute_url())

class UpdatePost(UpdateView):
    model = Post
    fields = ['title','post']

    def dispatch(self, request, *args, **kwargs):
        ru = get_object_or_404(Post,pk=kwargs['pk'])
        if ru.author==request.user:
            return super(UpdatePost, self).dispatch(
            request, *args, **kwargs)
        raise Http404("permission denied")


@method_decorator(staff_member_required, name='dispatch')
class DeletePost(DeleteView):
    model = Post
    success_url = reverse_lazy('home:index')

@login_required
def post_comment(request,post_id):
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.cleaned_data.get('comment')
        com = Comment()
        com.comment = comment
        com.post = Post.objects.get(pk=post_id)
        com.author_id = request.user
        com.date = datetime.now()
        com.save()

        return HttpResponse("<h1>"+str(com.get_last_id())+"</h1>")

    return render(request, 'home/comment_form.html', {'form': form,'post_id':post_id})


@login_required
def comment_delete(request,post_id,cmnt_id):
    post = get_object_or_404(Post,pk=post_id)
    cmnt = get_object_or_404(Comment,pk=cmnt_id)
    if cmnt.author_id==request.user or request.user.is_superuser or post.user==request.user:
        cmnt.delete()
        return redirect(cmnt.get_absolute_url())
    raise Http404('permission denied')

@login_required
def comment_update(request,cmnt_id):
    cmnt = get_object_or_404(Comment,pk=cmnt_id)
    form = CommentForm(request.POST or None)

    if cmnt.author_id==request.user:
        if form.is_valid():
            comment = form.cleaned_data.get('comment')
            cmnt.comment = comment
            cmnt.date = datetime.now()
            cmnt.save()

            return redirect(cmnt.get_absolute_url())
        else:
            raise Http404('something went wrong')
    raise Http404('permission denied')


@login_required
def comment_vote_handler(request,post_id,cmnt_id,vote_type):
    vote_type=int(vote_type)
    obj = CommentVote()
    query = CommentVote.objects.filter(user=request.user,cmnt_id=cmnt_id)
    if len(query)==0:
        prev=0
        obj.user = request.user
        obj.post_id = post_id
        obj.cmnt_id = cmnt_id
        obj.vote_type = prev
    else:
        obj=query[0]
        prev=obj.vote_type
    #upvote
    if vote_type==1:
        if prev==1:
            raise Http404('already upvoted')
        else:
            obj.vote_type+=1
    elif vote_type==0:
        if prev==-1:
            raise Http404('already downvoted')
        else:
            obj.vote_type-=1

    obj.save()
    return redirect(obj.get_absolute_url())


@login_required
def post_vote_handler(request,post_id,vote_type):
    vote_type=int(vote_type)
    obj = PostVote()
    query = PostVote.objects.filter(user=request.user,post_id=post_id)
    if len(query)==0:
        prev=0
        obj.user = request.user
        obj.post_id = post_id
        obj.vote_type = prev
        print '****','not found'
    else:
        obj=query[0]
        prev=obj.vote_type
    #upvote
    if vote_type==1:
        if prev==1:

home/templates/home/def_form_template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
    <div class="col-md-10">{{ field }}</div>
</div>
{% endfor %}

home/templates/home/faq_page.html
{% extends 'home/simple_master.html' %}
{% load staticfiles %}
{% block custom-css %}

{% endblock %}
{% block body %}
<div class="faq-wrapper">
{% for f in faq %}
       <div class="single-faq">
        <h3>{{ f.question }}</h3>
        <p>{{ f.answer }}</p>
       </div>
   </div>
{% endfor %}
{% endblock %}

home/templates/home/login_form.html
{% extends 'home/simple_master.html' %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="login-panel-wrapper">
                            <div>
                                <div class="panel-header"><h4>login</h4></div>
                                <input id="username" type="text" name="username" maxlength="100" required />
                                <input id="password" type="password" name="password" maxlength="100" required />
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <button type="submit" class=" login-btn btn btn-success">submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SUSTForum</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{%  static 'home/css/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/animate.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/index.css' %}">
    {% block custom-css %}
    {% endblock %}
</head>
<body>
 <div class="menu-outer">
    <nav class="navbar">
      <ul class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img src="" alt=""></a>
        </div>
        <ul class="nav navbar-nav my-navbar-nav">
          <li><a href="{% url 'home:index' %}">Home</a></li>
          <li><a href="{% url 'home:new_post' %}">Post</a></li>
          <li><a href="{% url 'home:faq' %}">Faq</a></li>
          <li><a href="#">About</a></li>
        </ul>
        <ul class="nav navbar-nav drop-navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li class="dropdown wow fadeInDown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user }}<span class="fa fa-caret-down" style="margin-left: 10px"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="" href="{% url 'home:profile' user.pk %}"><i class="fa fa-user" style="margin-right: 10px"></i>profile</a></li>
                        <li><a class="" href="{% url 'home:logout' %}"><i class="fa fa-sign-out" style="margin-right: 10px"></i>logout</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="{% url 'home:register' %}"><span class="fa fa-user"></span> Sign Up</a></li>
                <li><a href="{% url 'home:login' %}"><span class="fa fa-sign-in"></span> Login</a></li>
            {% endif %}
        </ul>
      </ul>
    </nav>
  </div>
  <!-- Navigation Menu End -->
  <!-- contents start-->
  <div class="container">
    <div class="col-md-9 force-margin">
        {% block body %}
        {% endblock %}
    </div>
    <div class="col-md-3">
        <div class="search-box">
            <form method='GET' action="{% url 'home:index' %}">
            <input type="text" name="q" placeholder="search" value="{{ request.GET.q }}"/>
            <input type="submit" value="&#xf002" id="submitButton">
        </form>
        </div>
        {% block side-opt %}

        {% endblock %}
        {% if user.is_authenticated %}
            <div class="chat-room" id="chat-room" data-room-id="{{ room.id }}" >
                <h3>live-discuss</h3>
                <div class="msgs" id="msgs">
                    <ul id="msgs-list">

                    </ul>
                </div>
                <div class="rep">
                    <textarea class="input" id="input"></textarea>
                    <button class="send btn btn-success" id="send">send</button>
                </div>
            </div>

        {% endif %}
    </div>
  </div>
  <!-- contents end-->
  <!-- Footer Start -->
  <div id="footer">
    <div class="">All Right Reserved</div>
    <div class="">Powered by <a href="#">Dept. of SUST</a></div>
  </div>
  <!-- Footer End -->
 <script src="{% static 'home/js/jquery.min.js' %}"></script>
 <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
 <script src="{% static 'home/js/wow.min.js' %}"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
 <script src="{% static "home/js/chat.js" %}"></script>
{% block custom-js %}

{% endblock %}
</body>
</html>

home/templates/home/post-form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
    <div class="col-md-10">{{ field }}</div>
</div>
{% endfor %}

home/templates/home/post_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

home/templates/home/post_form.html
{% extends 'home/simple_master.html' %}
{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/post_form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/post_form_template.html
<div class="form-group text-attr">
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'home/js/nice-edit.js' %}"></script>
        <script type="text/javascript">
            //<![CDATA[
            bkLib.onDomLoaded(function () {
                new nicEditor({
                    fullPanel: true
                }).panelInstance('post-body');
            });
            //]]>
        </script>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.title.errors }}</span>
    </div>
    <label class="control-label col-sm-2" >{{ form.title.label_tag }}</label>
    {% load widget_tweaks %}
    <div class="col-md-10 title-text">{{ form.title|attr:"rows:2" }}</div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.post.errors }}</span>
    </div>
    <label class="control-label col-sm-2" >{{ form.post.label_tag }}</label>
    <div class="col-md-10">
        <textarea id="post-body" name="post">
            {{ form.post.value }}
        </textarea>
    </div>
</div>

home/templates/home/post_update_form.html
<div class="form-group text-attr">
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'home/js/nice-edit.js' %}"></script>
        <script type="text/javascript">
            //<![CDATA[
            bkLib.onDomLoaded(function () {
                new nicEditor({
                    fullPanel: true
                }).panelInstance('post-body');
            });
            //]]>
        </script>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.title.errors }}</span>
    </div>
    <label class="control-label col-sm-2" >{{ form.title.label_tag }}</label>
    {% load widget_tweaks %}
    <div class="col-md-10 title-text">{{ form.title|attr:"rows:2" }}</div>
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ form.post.errors }}</span>
    </div>
    <label class="control-label col-sm-2" >{{ form.post.label_tag }}</label>
    <div class="col-md-10">
        <textarea id="post-body" name="post">
            Write your post here...
        </textarea>
    </div>
</div>

home/templates/home/temp_cmnt.html
<div class="single-comment" id="clone" data-href="{% url 'home:comment_update' 222 %}">
                <div class="old-cmnt" id="old" style="display: block">
                    <div class="row">
                        <div class="cmnt-avatar col-md-1"><img class="avatar-img" src="" alt=""></div>
                        <div class="avatar-info col-md-11">
                            <p class="cmnt-author">{{ user }}</p>
                            <p class="cmnt-time">now</p>
                        </div>
                    </div>
                    <h5 class="cmnt-body">comment</h5>
                </div>

                <div class="new-comment" style="display: none" id="new">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-6 cmnt-author">
                                {% if user.is_authenticated %}
                                    <h5><span >{{ user }}</span> says ...</h5>
                                {% else %}
                                    <h5>(login required) <span >{{ user }}</span> says...</h5>
                                {% endif %}
                            </div>
                            <div class="col-sm-6 cmnt-submit">
                                <button type="submit" onclick="" class="my-btn btn-success pull-right">update</button>
                                <button type="submit" onclick="" class="my-btn btn-danger pull-right">cancel</button>
                            </div>
                        </div>
                        <textarea class="new-cmnt-textarea" name="comment" rows="2">comment</textarea>
                    </form>
                </div>

                <div class="cmnt-option" id="#btns">
                    <form method="POST" action="">
                    {% csrf_token %}
                        <button type="submit" data-href="{% url 'home:comment_delete' 111 222 %}" class="confirm-delete cmnt-btn cmnt-delete-btn">delete</button>
                    </form>
                    <button class="cmnt-btn cmnt-edit-btn" onclick="">edit</button>
                </div>
                <div class="cmnt-opt-btns">
                    <div class="cmnt-reply" id="#replyopt">
                        <a class="cmnt-vote cmnt-upvote" onclick="" data-href="{% url 'home:comment_vote' 111 222 1 %}">
                            <i class="fa fa-caret-up up"></i>
                        </a>
                        <span class="cmnt-vote-display" style="font-weight: bold">0</span>
                        <a class="cmnt-vote cmnt-downvote" onclick="" data-href="{% url 'home:comment_vote' 111 222 0 %}">
                            <i class="fa fa-caret-down down"></i>
                        </a>
                    </div>
                </div>
            </div>